[build]
publish = "dist"
command = "npm run production"

[[headers]]
for = "/*"
[headers.values]
Permissions-Policy = "interest-cohort=()"

[[redirects]]
from = "https://iamdeveloper.com/*"
to = "https://www.nickyt.co/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.iamdeveloper.com/*"
to = "https://www.nickyt.co/:splat"
status = 301
force = true

[[redirects]]
from = "/posts/*"
to = "/blog/:splat"
status = 301
force = true

[[redirects]]
from = "/talks"
to = "/pages/talks"
status = 302
force = true

[[redirects]]
from = "/uses"
to = "/pages/uses"
status = 302
force = true

[[redirects]]
from = "/news"
to = "https://OneTipAWeek.com"
status = 302
force = true

[[redirects]]
from = "/pages/newsletter/*"
to = "https://OneTipAWeek.com"
status = 302
force = true

[[redirects]]
from = "https://pod.iamdeveloper.com/2065897/*"
to = "https://nickyt.co"
status = 302
force = true

[[redirects]]
from = "https://pod.iamdeveloper.com/*"
to = "https://nickscuts.buzzsprout.com/2065897/:splat"
status = 302
force = true

[[redirects]]
from = "https://pod.nickyt.co/2065897/*"
to = "https://nickyt.co"
status = 301
force = true

[[redirects]]
from = "https://pod.nickyt.co/*"
to = "https://nickyt.co"
status = 302
force = true

[[redirects]]
from = "https://vscodetips.com/"
to = "https://nickyt.co"
status = 301
force = true

[[redirects]]
from = "/coc/*"
to = "/pages/coc/:splat"
status = 301
force = true

[[redirects]]
from = "https://discord.iamdeveloper.com/*"
to = "https://discord.gg/FkGSHMxbTe"
status = 301
force = true

# Thanks two Phils! https://www.hawksworx.com/blog/alias-your-mastodon-username-to-your-domain-with-one-netlify-config-setting/
[[redirects]]
from = "/.well-known/webfinger"
to = "https://hachyderm.io/.well-known/webfinger?resource=acct:nickytonline@hachyderm.io"
status = 200

[[redirects]]
from = "/schedule/"
to = "/pages/stream-schedule/"
status = 301
force = true

[[redirects]]
from = "/newsletter.rss"
to = "https://buttondown.email/nickytonline/rss"
status = 302
force = true

# talks

[[redirects]]
from = "/storybook2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vRVZS5fW795LoPUioxbpIO0k0gaUA7g-J9je8bCaoHKGl678_NgbpNXdsiw3HIrt5BHTLr_l2MmvaNU/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/debug2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vSPMh7JIhImdVWJxUJQOICyib6uETKfpXZ9PDpO-6p-qxn3gW2QxKJHj2ofMxi_s31gAhnwl0nWugOQ/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/hacktoberfest2020/"
to = "https://www.digitalocean.com/community/tech_talks/getting-the-most-out-of-open-source"
status = 302
force = true

[[redirects]]
from = "/lightning2020/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vRHfnRD5-ZTiPbBZsT3fNtsB4KcKiemJCLhUxPjtGE5nR2JxmtbtK3_iLSeYbg3ctgVAJEiqPSnAVUQ/pub?start=false&loop=false&delayms=3000"
status = 302
force = true

[[redirects]]
from = "/stream2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vR0cBGMDt11jQ3tP-Z8UPf6BFYXLWX8XzsmfCb26RAYd5gX_ct662YJQrk-fCVp0MOv9tUW4mvBgam8/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/hacktoberfest2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vTUIycMPdV3wRo_nLOhfpiYiUYeML5Bvu4aA1W692VOsvA5p3XIQEC-Y5fPEGWk4uGkpP_z2QNJkJGR/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/codementor2022/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vQWw0j07xs3gzh8QOUQH6V5kdtX6xPCMmdnSWBfcniNUgqPTYDeMm2CB3BzdiTG0LOKKKg-Ky8r21ko/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/11tyMeetupMay2022/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vSSj2W1UDxVH2nNBhH0O_5CNia76ri2C0fx8jygK1ZDE6EXs6_CFUZQp64-zyciFaV7xhJWFSYoLsb7/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/ChicagoFresh/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vQaaGHPbIdb7FPrzbK_1zI1VDhsrEkGJdmwwjRVLoxVz8USPwnw7Jc0kAfDau9gDw22jr2pvd3CB87c/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/fresh/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vRr2ClzHyIfhamV8rRh92UN5XLDDJKY4E5322hvy_vp6X0cKp3YSayfaSxE6jYG1C8brP3DgZqw6M6u/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/fresh-demo/"
to = "https://fresh-talk-demo.deno.dev/"
status = 302
force = true

[[redirects]]
from = "/cypress2023/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vSrKxG3lMKiBXTGH5oDRa4Xn2a23ibQ0jn4iw0UK9VJaoLIF7Fl5GVAEJ5enQ6oEA93huBSBxX2lUdi/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/pages/newsletter-archives/*"
to = "https://buttondown.email/nickytonline/archive/"
status = 302
force = true

[[redirects]]
from = "/hack-for-la-2023/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vTby0GBEWTN0uPPvDlZ5QZKEMnvuKLm-HrqybOiAarJfPWIlMDMOgoqj3vYnS0RA4EuIw7sZAKb23G0/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/pages/subscription-confirmed"
to = "/pages/subscribed"
status = 302
force = true

[[redirects]]
from = "/slides/fresh/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vTMFTFQnsUf3XDe-j-Av-ZcMB6YYXXqyOGQIsj0yHvBbRE5mXdfVmb4gpG-qnPWcDYDbZp21pEu32LI/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/demos/fresh/"
to = "https://so-fresh-demo.deno.dev/"
status = 302
force = true

[[redirects]]
from = "/slides/ext-e2e"
to = "https://docs.google.com/presentation/d/e/2PACX-1vQtuydI6RpHZ0lrdXrerx_jf8-KvFZRs9fS0QOuPkMv6svIon5I1JWGfJEDqD91XK434sfseStbHPZQ/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/slides/confoo-fresh"
to = "https://docs.google.com/presentation/d/e/2PACX-1vQsCDGiQMZYh-y90ojCTrWdnjbvYaS4iFH9lDnZcLl0lTH5IpTQnSlfloXDSvWuk9PqNYnJnnlY0UXc/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/slides/ts-generics"
to = "https://docs.google.com/presentation/d/e/2PACX-1vSQbVQf2G2-lWHloR_3jx16iCVI4xGyAXkhM11zFhqnMgGEp_Dc5LPeqkydnU9JcE-NvorMcZH_iwim/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/slides/compose-24"
to = "https://docs.google.com/presentation/d/1-YBGThyLLuFHPhgQ7_0xAHJGlLPPHPR6p4Gwgt5nWfI/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/slides/ato24"
to = "https://docs.google.com/presentation/d/e/2PACX-1vSQtlWFl3LA9mSC9iqML5GItoqwYLLRtvW4WJEyX4cA-jxsiTyh3eckd7P-hklBF1k0N9SVx0SoyVT_/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/slides/xtreme24"
to = "https://docs.google.com/presentation/d/e/2PACX-1vTdVxuIPmNwqX_fg2vi58v7lk9Vv73azN-TbKn4omb83SOkfgpVH-pQnKawosEIKPkHHgFVAXED3jyo/pub?start=false&loop=false&delayms=5000"
status = 302
force = true

[[redirects]]
from = "/demos/xtreme24"
to = "https://github.com/nickytonline/xtremejs-2024-demo"
status = 302
force = true

[[redirects]]
from = "/pages/stream-schedule/*"
to = "https://nickyt.live/schedule/:splat"
status = 301
force = true

[[redirects]]
from = "/pages/streaming/*"
to = "https://nickyt.live/:splat"
status = 301
force = true

[[redirects]]
from = "/copilot-extension-guide/*"
to = "/blog/creating-your-first-github-copilot-extension-a-step-by-step-guide-28g0/:splat"
staus = 301
force = true

[[redirects]]
from = "/bsky/*"
to = "https://bsky.app/profile/nickyt.online/:splat"
staus = 301
force = true

[[redirects]]
from = "/ato-fresh/"
to = "https://ato-fresh.deno.dev/"
status = 302
force = true

[[redirects]]
from = "https://nickyt.online/*"
to = "https://bsky.app/profile/nickyt.online/:splat"
staus = 301
force = true

## talk redirects to nickyt.live

[[redirects]]
from = "/pages/talks/appwrite-hacktoberfest-kickoff-2021"
to = "https://nickyt.live/talks/appwrite-hacktoberfest-kickoff-2021"
status = 301
force = true

[[redirects]]
from = "/pages/talks/asking-coding-questions-virtual-coffee-lunch-and-learn-2022"
to = "https://nickyt.live/talks/asking-coding-questions-virtual-coffee-lunch-and-learn-2022"
status = 301
force = true

[[redirects]]
from = "/pages/talks/automate-syndication-and-ownership-of-your-content-with-eleventy-eleventy-meetup-2022"
to = "https://nickyt.live/talks/automate-syndication-and-ownership-of-your-content-with-eleventy-eleventy-meetup-2022"
status = 301
force = true

[[redirects]]
from = "/pages/talks/back-to-basics-why-html-forms-still-rule-the-web-confoo-2025"
to = "https://nickyt.live/talks/back-to-basics-why-html-forms-still-rule-the-web-confoo-2025"
status = 301
force = true

[[redirects]]
from = "/pages/talks/career-lab-q2-2023-watch-your-mentors-interview-each-other"
to = "https://nickyt.live/talks/career-lab-q2-2023-watch-your-mentors-interview-each-other"
status = 301
force = true

[[redirects]]
from = "/pages/talks/debugging-javascript-virtual-coffee-lunch-and-learn"
to = "https://nickyt.live/talks/debugging-javascript-virtual-coffee-lunch-and-learn"
status = 301
force = true

[[redirects]]
from = "/pages/talks/end-to-end-testing-for-browser-extensions-confoo-2024"
to = "https://nickyt.live/talks/end-to-end-testing-for-browser-extensions-confoo-2024"
status = 301
force = true

[[redirects]]
from = "/pages/talks/end-to-end-testing-for-browser-extensions-xtremejs-2024"
to = "https://nickyt.live/talks/end-to-end-testing-for-browser-extensions-xtremejs-2024"
status = 301
force = true

[[redirects]]
from = "/pages/talks/end-to-end-testing-with-cypress-the-collab-lab-tech-talks"
to = "https://nickyt.live/talks/end-to-end-testing-with-cypress-the-collab-lab-tech-talks"
status = 301
force = true

[[redirects]]
from = "/pages/talks/expert-panel--future-of-testing-front-end-test-fest-2023"
to = "https://nickyt.live/talks/expert-panel--future-of-testing-front-end-test-fest-2023"
status = 301
force = true

[[redirects]]
from = "/pages/talks/expert-panel--trending-tools-and-frameworks-front-end-test-fest-2022"
to = "https://nickyt.live/talks/expert-panel--trending-tools-and-frameworks-front-end-test-fest-2022"
status = 301
force = true

[[redirects]]
from = "/pages/talks/fresh--a-full-stack-web-framework-for-deno-all-things-open-2024"
to = "https://nickyt.live/talks/fresh--a-full-stack-web-framework-for-deno-all-things-open-2024"
status = 301
force = true

[[redirects]]
from = "/pages/talks/fresh--a-full-stack-web-framework-for-deno-confoo-2024"
to = "https://nickyt.live/talks/fresh--a-full-stack-web-framework-for-deno-confoo-2024"
status = 301
force = true

[[redirects]]
from = "/pages/talks/fresh--a-full-stack-web-framework-for-deno-global-summit-for-nodejs-24"
to = "https://nickyt.live/talks/fresh--a-full-stack-web-framework-for-deno-global-summit-for-nodejs-24"
status = 301
force = true

[[redirects]]
from = "/pages/talks/fresh--a-new-full-stack-web-framework-for-deno-chicagojs-2022"
to = "https://nickyt.live/talks/fresh--a-new-full-stack-web-framework-for-deno-chicagojs-2022"
status = 301
force = true

[[redirects]]
from = "/pages/talks/fresh--a-new-full-stack-web-framework-for-deno-node-congress"
to = "https://nickyt.live/talks/fresh--a-new-full-stack-web-framework-for-deno-node-congress"
status = 301
force = true

[[redirects]]
from = "/pages/talks/getting-started-with-streaming-on-twitch-virtual-coffee-lunch-and-learn-2021"
to = "https://nickyt.live/talks/getting-started-with-streaming-on-twitch-virtual-coffee-lunch-and-learn-2021"
status = 301
force = true

[[redirects]]
from = "/pages/talks/getting-the-most-out-of-open-source-digitalocean-tech-talk-2020"
to = "https://nickyt.live/talks/getting-the-most-out-of-open-source-digitalocean-tech-talk-2020"
status = 301
force = true

[[redirects]]
from = "/pages/talks/getting-the-most-out-of-open-source-hack-for-la-2023"
to = "https://nickyt.live/talks/getting-the-most-out-of-open-source-hack-for-la-2023"
status = 301
force = true

[[redirects]]
from = "/pages/talks/lets-create-a-github-copilot-extension-all-things-open-ai-2025"
to = "https://nickyt.live/talks/lets-create-a-github-copilot-extension-all-things-open-ai-2025"
status = 301
force = true

[[redirects]]
from = "/pages/talks/lets-create-a-github-copilot-extension-confoo-2025"
to = "https://nickyt.live/talks/lets-create-a-github-copilot-extension-confoo-2025"
status = 301
force = true

[[redirects]]
from = "/pages/talks/storybook-2021-the-collab-lab-tech-talks"
to = "https://nickyt.live/talks/storybook-2021-the-collab-lab-tech-talks"
status = 301
force = true

[[redirects]]
from = "/pages/talks/tools-for-web-developers-live-coding-and-debugging-codementor-2022"
to = "https://nickyt.live/talks/tools-for-web-developers-live-coding-and-debugging-codementor-2022"
status = 301
force = true

[[redirects]]
from = "/pages/talks/why-html-forms-still-rule-the-web-netlify-compose-2024"
to = "https://nickyt.live/talks/why-html-forms-still-rule-the-web-netlify-compose-2024"
status = 301
force = true

[[redirects]]
from = "/pages/talks/words-matter-conventional-comments-virtual-coffee-lightning-talks-2020"
to = "https://nickyt.live/talks/words-matter-conventional-comments-virtual-coffee-lightning-talks-2020"
status = 301
force = true

[[redirects]]
from = "/pages/talks/zero-trust--from-airports-to-identity-aware-proxies-sreday-london-2025-q1"
to = "https://nickyt.live/talks/zero-trust--from-airports-to-identity-aware-proxies-sreday-london-2025-q1"
status = 301
force = true

[[redirects]]
from = "/pages/talks/zero-trust--from-airports-to-identity-aware-proxies-sreday-redmond-2025-q2"
to = "https://nickyt.live/talks/zero-trust--from-airports-to-identity-aware-proxies-sreday-redmond-2025-q2"
status = 301
force = true

[[redirects]]
from = "/pages/talks/zero-trust--from-airports-to-identity-aware-proxies-sreday-san-francisco-2025-q2"
to = "https://nickyt.live/talks/zero-trust--from-airports-to-identity-aware-proxies-sreday-san-francisco-2025-q2"
status = 301
force = true
