[build]
publish = "dist"
command = "./stackbit-build.sh"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
from = "/about"
to = "/pages/about"
status = 301
force = true

[[redirects]]
from = "/live-coding"
to = "/pages/live-coding"
status = 301
force = true

[[redirects]]
from = "/talks"
to = "/pages/talks"
status = 301
force = true

[[redirects]]
from = "/uses"
to = "/pages/uses"
status = 301
force = true

[[redirects]]
from = "/thanks"
to = "/pages/thanks"
status = 301
force = true

[[redirects]]
from = "/contact"
to = "/pages/contact"
status = 301
force = true

[[redirects]]
from = "https://webflow.iamdeveloper.com/*"
to = "http://nick-taylors-first-project.webflow.io:splat"
status = 301
force = true

[[redirects]]
from = "https://vscode.iamdeveloper.com/*"
to = "/posts/my-visual-studio-code-setup-2ima/"
status = 301
force = true

[[redirects]]
from = "https://osx.iamdeveloper.com/*"
to = "https://gist.github.com/nickytonline/378e7a6584542112f53c0067a6a4684c:splat"
status = 301
force = true

[[redirects]]
from = "https://story.iamdeveloper.com/*"
to = "https://github.com/nickytonline/js-montreal-storybook-talk-2017-06-13:splat"
status = 301
force = true

[[redirects]]
from = "https://resources.iamdeveloper.com/*"
to = "https://gist.github.com/nickytonline/5cf16c4adab6c558552d384db4cc2057:splat"
status = 301
force = true

[[redirects]]
from = "https://mac.iamdeveloper.com/*"
to = "/posts/my-mac-setup-2m05/"
status = 301
force = true

[[redirects]]
from = "https://gitaliases.iamdeveloper.com/*"
to = "/posts/my-git-aliases-5dea/"
status = 301
force = true

[[redirects]]
from = "https://cv.iamdeveloper.com/*"
to = "https://stackoverflow.com/cv/nickytonline:splat"
status = 301
force = true

# Redirects for old URLs of blog posts pre-2019
[[redirects]]
from = "/consider-using-typescript/"
to = "/posts/why-you-might-want-to-consider-using-typescript-6j3/"
status = 301
force = true

[[redirects]]
from = "/2018-resolutions/"
to = "/posts/2018-resolutions-1deo/"
status = 301
force = true

[[redirects]]
from = "/my-mac-setup/"
to = "/posts/my-mac-setup-2m05/"
status = 301
force = true

[[redirects]]
from = "/2018-03-26-getting-started-with-react-storybook/"
to = "/posts/getting-started-with-react-storybook-9jh/"
status = 301
force = true

[[redirects]]
from = "/2018-08-25-my-git-aliases/"
to = "/posts/my-git-aliases-5dea/"
status = 301
force = true

[[redirects]]
from = "/2018-09-02-setting-up-storybook-for-preact/"
to = "/posts/setting-up-storybook-for-preact-p5a/"
status = 301
force = true

[[redirects]]
from = "/2018-12-29-2018-year-in-review/"
to = "/posts/my-2018-year-in-review-2f0k/"
status = 301
force = true

[[redirects]]
from = "/blog/2020-01-21-a-new-year-a-new-start-im-joining-the-dev-team/"
to = "/posts/a-new-year-a-new-start-i-m-joining-the-dev-team-3ap0/"
status = 301
force = true

[[redirects]]
from = "/2018-resolutions/"
to = "/posts/2018-resolutions-1deo/"
status = 301
force = true

[[redirects]]
from = "/great-pr/"
to = "https://dev.to/nickytonline/great-examples-of-issues-and-pull-requests-2nne"
status = 301
force = true

[[redirects]]
from = "/pair/"
to = "https://airtable.com/shrr10gmF5YxhY3W0"
status = 301
force = true

[[redirects]]
from = "/hacktoberfest2020/"
to = "https://www.digitalocean.com/community/tech_talks/getting-the-most-out-of-open-source"
status = 301
force = true

[[redirects]]
from = "/lightning2020/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vRHfnRD5-ZTiPbBZsT3fNtsB4KcKiemJCLhUxPjtGE5nR2JxmtbtK3_iLSeYbg3ctgVAJEiqPSnAVUQ/pub?start=false&loop=false&delayms=3000"
status = 301
force = true

[[redirects]]
from = "/storybook2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vRVZS5fW795LoPUioxbpIO0k0gaUA7g-J9je8bCaoHKGl678_NgbpNXdsiw3HIrt5BHTLr_l2MmvaNU/pub?start=false&loop=false&delayms=5000"
status = 301
force = true

[[redirects]]
from = "/debug2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vSPMh7JIhImdVWJxUJQOICyib6uETKfpXZ9PDpO-6p-qxn3gW2QxKJHj2ofMxi_s31gAhnwl0nWugOQ/pub?start=false&loop=false&delayms=5000"
status = 301
force = true

[[redirects]]
from = "https://youtube.iamdeveloper.com/*"
to = "https://www.youtube.com/channel/UCBLlEq0co24VFJIMEHNcPOQ/:splat"
status = 301
force = true

[[redirects]]
from = "https://livecoding.ca/learn-rust/*"
to = "https://www.youtube.com/playlist?list=PLcR4ZgxWXeIAFF1MYfuoGa6FeksKcMz-O"
status = 301
force = true

[[redirects]]
from = "https://livecoding.ca/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.livecoding.ca/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://javascripthours.com/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.javascripthours.com/*"
to = "https://twitch.tv/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "https://updates.iamdeveloper.com/*"
to = "https://timeline.iamdeveloper.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://newsletter.iamdeveloper.com/*"
to = "https://buttondown.email/nickytonline/:splat"
status = 301
force = true

[[redirects]]
from = "/stream2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vR0cBGMDt11jQ3tP-Z8UPf6BFYXLWX8XzsmfCb26RAYd5gX_ct662YJQrk-fCVp0MOv9tUW4mvBgam8/pub?start=false&loop=false&delayms=5000"
status = 301
force = true

[[redirects]]
from = "/hacktoberfest2021/"
to = "https://docs.google.com/presentation/d/e/2PACX-1vTUIycMPdV3wRo_nLOhfpiYiUYeML5Bvu4aA1W692VOsvA5p3XIQEC-Y5fPEGWk4uGkpP_z2QNJkJGR/pub?start=false&loop=false&delayms=5000"
status = 301
force = true
