[build]
publish = "public"
command = "./stackbit-build.sh"

[[redirects]]
from = "https://webflow.iamdeveloper.com/*"
to = "http://nick-taylors-first-project.webflow.io:splat"
status = 301
force = true

[[redirects]]
from = "https://vscode.iamdeveloper.com/*"
to = "/posts/my-visual-studio-code-setup-2ima/"
status = 301
force = true

[[redirects]]
from = "https://osx.iamdeveloper.com/*"
to = "https://gist.github.com/nickytonline/378e7a6584542112f53c0067a6a4684c:splat"
status = 301
force = true

[[redirects]]
from = "https://story.iamdeveloper.com/*"
to = "https://github.com/nickytonline/js-montreal-storybook-talk-2017-06-13:splat"
status = 301
force = true

[[redirects]]
from = "https://resources.iamdeveloper.com/*"
to = "https://gist.github.com/nickytonline/5cf16c4adab6c558552d384db4cc2057:splat"
status = 301
force = true

[[redirects]]
from = "https://mac.iamdeveloper.com/*"
to = "/posts/my-mac-setup-2m05/"
status = 301
force = true

[[redirects]]
from = "https://gitaliases.iamdeveloper.com/*"
to = "/posts/my-git-aliases-5dea/"
status = 301
force = true

[[redirects]]
from = "https://cv.iamdeveloper.com/*"
to = "https://stackoverflow.com/cv/nickytonline:splat"
status = 301
force = true

# Redirects for old URLs of blog posts pre-2019
[[redirects]]
from = "/consider-using-typescript/"
to = "/posts/why-you-might-want-to-consider-using-typescript-6j3/"
status = 301
force = true

[[redirects]]
from = "/2018-resolutions/"
to = "/posts/2018-resolutions-1deo/"
status = 301
force = true

[[redirects]]
from = "/my-mac-setup/"
to = "/posts/my-mac-setup-2m05/"
status = 301
force = true

[[redirects]]
from = "/2018-03-26-getting-started-with-react-storybook/"
to = "/posts/getting-started-with-react-storybook-9jh/"
status = 301
force = true

[[redirects]]
from = "/2018-08-25-my-git-aliases/"
to = "/posts/my-git-aliases-5dea/"
status = 301
force = true

[[redirects]]
from = "/2018-09-02-setting-up-storybook-for-preact/"
to = "/posts/setting-up-storybook-for-preact-p5a/"
status = 301
force = true

[[redirects]]
from = "/2018-12-29-2018-year-in-review/"
to = "/posts/my-2018-year-in-review-2f0k/"
status = 301
force = true

