name: Get latest newsletter archives
on:
  schedule:
    # 14:15 UTC on Sunday
    - cron: '15 14 * * SUN'
  workflow_dispatch:

jobs:
  update_profile_data:
    name: Get latest newsletter archives
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get Newsletter Archives
        env:
          DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
        run: |
          npm install
          node bin/generateNewsletterArchive.mjs
      - name: Setup git config
        run: |
          git config user.name 'token-generator-app[bot]'
          git config user.email '82042599+token-generator-app[bot]@users.noreply.github.com'
      - name: PR for Newsletter Archive Updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bin/pr-news-archives.sh
